### ISSUE TITLE
Dependency on Python not specified

### ISSUE THREAD

**Issue by dgthanhan** [evolus/pencil#15]
Originally posted by @Craig-Fisk
Following the instructions I cloned the repo, ensured I am running node 4.2+ (currently 4.2.2) and tried to run npm install and got the following errors:

```
$ npm install
npm WARN optional dep failed, continuing appdmg-tf@0.3.11
npm WARN optional dep failed, continuing 7zip-bin-osx@0.0.1

> nslog@3.0.0 install C:\git\pencil-v3\node_modules\electron-rebuild\node_modules\nslog
> node-gyp rebuild


C:\git\pencil-v3\node_modules\electron-rebuild\node_modules\nslog>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node  rebuild )
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
gyp ERR! stack     at failNoPython (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:116:14)
gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:71:11
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:82:15)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\git\pencil-v3\node_modules\electron-rebuild\node_modules\nslog
gyp ERR! node -v v4.2.2
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v4.2.2
npm ERR! npm  v2.14.7
npm ERR! code ELIFECYCLE

npm ERR! nslog@3.0.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the nslog@3.0.0 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the nslog package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls nslog
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\git\pencil-v3\npm-debug.log
```
Am I simply missing Python? If so this should be included in the instructions

**Comment by dgthanhan** [comment]
From @mbrainiac:
On Windows you need to install Python (2.7), Visual Studio ( you can download Community version from https://www.visualstudio.com/products/free-developer-offers-vs) and Git.

**Comment by sTiKyt** [comment]
@dgthanhan this repository seems outdated, please post your Issue to our fork! We'll updаte it soon!
https://github.com/DarkSecDevelopers/RePencil
