### ISSUE TITLE
Pages aren't created & displayed to start actually using Pencil

### ISSUE THREAD

**Issue by cweagans** [evolus/pencil#196]
* Operating system: Arch Linux (current as of Nov 16)
* Pencil version: master (HEAD as of Nov 16) and v3.0.0-rc.1 -- tested both

* `electron` is installed via my package manager (presumably from installing atom, but it shouldn't matter)
* I clone this repo and `cd` into the `app` directory
* I run `npm install`
* I run `electron .`, which immediately starts the UI (which looks really nice, btw, although I think I agree with the other issues that say it's not dense enough)
* I click "Create new document", which pops open the bottom panel, which I assume is the area where pages should be listed?
* I'm not sure if there's a problem at this point, but the "Open a document" and "Create a New Document" buttons are still visible in the main part of the UI.
* I click "Add page" on the right side of the screen, which opens a new window to configure the page.
* I type "Test page" in the "Page title" field and leave everything else at the defaults (child of: none, page size: last used (960x600), background: transparent background), and then click "Create"
* At this point, I see the first problem: the add page dialog doesn't go away, and nothing appears to happen. Nothing is written to the shell I ran electron from, either.
* I click cancel to close the dialog, and then click "add page" again to go back into the add page dialog.
* This time, if I expand the "Child of" dropdown, I see that "test page" is now included in the list, along with "Untitled page". I *think* "Untitled page" is created when I click "create a new document", but I'm not sure because I never actually see a page. In any case, it looks like my page is getting created, but never gets displayed.
* I can confirm this by typing "asdf" in the title field by clicking the "Create" button a bunch of times and closing and reopening the dialog. The "Child of" dropdown now contains a number of "asdf" pages equal to the number of times I clicked "Create".

I'm not sure if I'm doing something wrong here, but just wanted to pass this along in case it will help.

**Comment by dgthanhan** [comment]
Electron eversion does matter in running Pencil.
Could you please post also the error console log?

**Comment by cweagans** [comment]
I'm running Electron v1.4.6, which is what is installed by `pacman`. Do I need a newer (or older) version?

I'm not sure what you mean by error console. Are you talking about the shell that I started Electron from? Or the actual DOM JS error console? If it's the former, here ya go:

```
cweagans@cockpit:~/Downloads/pencil/app$ electron .
Hardware acceleration disabled for Linux.
Platform: linux
Background web-printer started.
RENDERER started.
^C^C
```

If it's the latter, here is the contents of the console upon starting Pencil:

``` 
Uncaught Error: Module version mismatch. Expected 50, got 48.
Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check https://xhr.spec.whatwg.org/.
Uncaught ReferenceError: QueueHandler is not defined
Failed to load resource: net::ERR_FILE_NOT_FOUND
Failed to load resource: net::ERR_FILE_NOT_FOUND
Failed to load resource: net::ERR_FILE_NOT_FOUND
Failed to load resource: net::ERR_FILE_NOT_FOUND
Failed to load resource: net::ERR_FILE_NOT_FOUND
Failed to load resource: net::ERR_FILE_NOT_FOUND
Failed to load resource: net::ERR_FILE_NOT_FOUND
Failed to load resource: net::ERR_FILE_NOT_FOUND
Failed to load resource: net::ERR_FILE_NOT_FOUND
Failed to load resource: net::ERR_FILE_NOT_FOUND
Failed to load resource: net::ERR_FILE_NOT_FOUND
Failed to load resource: net::ERR_FILE_NOT_FOUND
Failed to load resource: net::ERR_FILE_NOT_FOUND
ENOENT: no such file or directory, stat '/home/cweagans/.pencil/privateCollection/PrivateCollection.xml'

Location: undefined (undefined)
Stacktrace:
	Error: ENOENT: no such file or directory, stat '/home/cweagans/.pencil/privateCollection/PrivateCollection.xml'
	    at Error (native)
	    at fs.statSync (fs.js:992:18)
	    at Object.fs.statSync (ELECTRON_ASAR.js:285:16)
	    at Object.PrivateCollectionManager.loadPrivateCollections (file:///home/cweagans/Downloads/pencil/app/pencil-core/privateCollection/privateCollectionManager.js:14:23)
	    at MyCollectionPane.initialize (file:///home/cweagans/Downloads/pencil/app/views/collections/MyCollectionPane.js:22:30)
	    at MyCollectionPane.BaseCollectionPane [as constructor] (file:///home/cweagans/Downloads/pencil/app/views/collections/BaseCollectionPane.js:85:10)
	    at new MyCollectionPane (file:///home/cweagans/Downloads/pencil/app/views/collections/MyCollectionPane.js:2:24)
	    at file:///home/cweagans/Downloads/pencil/app/lib/widget/Common.js:174:26
	    at Object.Dom.doOnChildRecursively (file:///home/cweagans/Downloads/pencil/app/pencil-core/common/util.js:514:36)
	    at Object.performAutoBinding (file:///home/cweagans/Downloads/pencil/app/lib/widget/Common.js:159:17)
Loading system stencils...
Failed to load resource
x is not defined

Location: undefined (undefined)
Stacktrace:
	ReferenceError: x is not defined
	    at eval (eval at pEval (file:///home/cweagans/Downloads/pencil/app/pencil-core/common/util.js:2064:35), <anonymous>:67:310962)
	    at pEval (file:///home/cweagans/Downloads/pencil/app/pencil-core/common/util.js:2064:35)
	    at file:///home/cweagans/Downloads/pencil/app/pencil-core/definition/shapeDefCollectionParser.js:213:9
	    at Object.Dom.workOn (file:///home/cweagans/Downloads/pencil/app/pencil-core/common/util.js:285:9)
	    at ShapeDefCollectionParser.parse (file:///home/cweagans/Downloads/pencil/app/pencil-core/definition/shapeDefCollectionParser.js:211:9)
	    at ShapeDefCollectionParser.parseURL (file:///home/cweagans/Downloads/pencil/app/pencil-core/definition/shapeDefCollectionParser.js:75:31)
	    at Object.CollectionManager.loadStencils (file:///home/cweagans/Downloads/pencil/app/pencil-core/definition/collectionManager.js:180:52)
	    at Object.Pencil.boot (file:///home/cweagans/Downloads/pencil/app/pencil-core/common/pencil.js:89:27)
	    at new ApplicationPane (file:///home/cweagans/Downloads/pencil/app/views/ApplicationPane.js:4:12)
	    at file:///home/cweagans/Downloads/pencil/app/lib/widget/Common.js:174:26
Failed to load resource
Loading stencils in: /home/cweagans/.pencil/stencils
 excluded: undefined
Failed to load resource
2 "stencils loaded."
Loading developer stencils...
Error: ENOENT: no such file or directory, stat '/home/cweagans/.pencil/exportTemplates/HTML'(…)
Error: ENOENT: no such file or directory, stat '/home/cweagans/.pencil/exportTemplates/Print'(…)
Error: ENOENT: no such file or directory, stat '/home/cweagans/.pencil/exportTemplates/ODT'(…)
add template ExportTemplate HTML
Type: Array[2]
Type: Array[2]
Type: Array[2]
Type: Array[2]
Type: Array[2]
Type: Array[2]
add template ExportTemplate Print
Type: Array[2]
Type: Array[2]
Type: Array[2]
Type: Array[2]
Type: Array[2]
Type: Array[2]
Type: Array[2]
Type: Array[2]
Type: Array[2]
Type: Array[2]
add template ExportTemplate Print
add template ExportTemplate ODT
fontManager is not defined

Location: undefined (undefined)
Stacktrace:
	ReferenceError: fontManager is not defined
	    at Object.Local.getInstalledFonts (file:///home/cweagans/Downloads/pencil/app/pencil-core/common/util.js:1033:17)
	    at Function.FontEditor._loadFontItems (file:///home/cweagans/Downloads/pencil/app/views/editors/FontEditor.js:32:28)
	    at Function.FontEditor._setupFontCombo (file:///home/cweagans/Downloads/pencil/app/views/editors/FontEditor.js:25:16)
	    at SharedFontEditor.setup (file:///home/cweagans/Downloads/pencil/app/views/editors/SharedFontEditor.js:20:16)
	    at Object.Pencil.boot (file:///home/cweagans/Downloads/pencil/app/pencil-core/common/pencil.js:141:41)
	    at new ApplicationPane (file:///home/cweagans/Downloads/pencil/app/views/ApplicationPane.js:4:12)
	    at file:///home/cweagans/Downloads/pencil/app/lib/widget/Common.js:174:26
	    at Object.Dom.doOnChildRecursively (file:///home/cweagans/Downloads/pencil/app/pencil-core/common/util.js:514:36)
	    at Object.performAutoBinding (file:///home/cweagans/Downloads/pencil/app/lib/widget/Common.js:159:17)
	    at onLoadDone (file:///home/cweagans/Downloads/pencil/app/lib/widget/Common.js:586:21)
```

This error appears immediately after clicking "Create new document": 

```
Uncaught ReferenceError: fontManager is not defined
```

And these messages appear after clicking "Create" in the "Add Page..." dialog:

```
Uncaught TypeError: Cannot read property 'canvas' of null
Uncaught ReferenceError: fontManager is not defined
Uncaught ReferenceError: QueueHandler is not defined
```

**Comment by dgthanhan** [comment]
The native fontManager module could not be loaded and caused the error. This is mainly because of the electron version.
If you would like to run Pencil in the development mode as you described, try invoking:
`$ npm run start:dev`
This will use the prebuilt electron version that the app depends on instead of the system one.

**Comment by cweagans** [comment]
Attempting to run Pencil in this way gives me the same errors. Looking in app/node_modules/.bin, I don't see `electron`. What else can I do to help debug?

**Comment by dgthanhan** [comment]
The following pair of commands:

```
$ npm install
$ npm run start:dev
```

should be run at the top level directory of the source tree which is the parent directory of 'app'.

**Comment by cweagans** [comment]
Thanks! That seemed to work. So it looks like the issue here is that my version of Electron is too new?

**Comment by dgthanhan** [comment]
The native module in Pencil does not work with your newer version of Electron. The provided `npm run start:dev` is to make sure that Pencil is launched with the expected Electron version which got installed by the `npm install`.

**Comment by h-2-0** [comment]
@ dgthanhan,

Hi! I tried the `npm install` and `npm run start:dev` combo to no avail when trying to run the Pencil 3.0.0-rc2 (other '3.0.X' versions get me the [blank page error](https://github.com/evolus/pencil/issues/350)  (issue [#350](https://github.com/evolus/pencil/issues/350) ). I still experience the same  issues described by @cweagans in his first post in here. It looks my electron version is 1.4.14
```
# ~/opt/pencil-3.0.0-rc.2/package.json 
{
  "name": "Pencil",
  "devDependencies": {
    "electron-builder": "13.3.0",
    "electron": "1.4.14",
    "rimraf": "^2.5.4"
  },

```



Here is my console log:

```
ELECTRON_ASAR.js:173 Uncaught Error: /home/user/opt/pencil-3.0.0-rc.2/app/lib/font-manager/linux/fontmanager.node: wrong ELF class: ELFCLASS64
util.js:325 Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check https://xhr.spec.whatwg.org/.
NotificationPopup.js:60 Uncaught ReferenceError: QueueHandler is not defined(anonymous function) @ NotificationPopup.js:60
desktop.js:77 Coud not found font command registry for  gnome-fallbacklinux @ desktop.js:77getDesktopFontConfig @ desktop.js:187(anonymous function) @ Common.js:581widget.reloadDesktopFont @ Common.js:580(anonymous function) @ Common.js:649
Common.js:646 GET file:///home/user/opt/pencil-3.0.0-rc.2/app/views/common/BuilderBasedDialog.xhtml?t=1515510871010_3344 net::ERR_FILE_NOT_FOUNDloadNext @ Common.js:646request.onreadystatechange @ Common.js:641
Common.js:646 GET file:///home/user/opt/pencil-3.0.0-rc.2/app/views/common/ToolBar.xhtml?t=1515510871010_3344 net::ERR_FILE_NOT_FOUNDloadNext @ Common.js:646request.onreadystatechange @ Common.js:641
Common.js:646 GET file:///home/user/opt/pencil-3.0.0-rc.2/app/views/common/WizardDialog.xhtml?t=1515510871010_3344 net::ERR_FILE_NOT_FOUNDloadNext @ Common.js:646request.onreadystatechange @ Common.js:641
Common.js:646 GET file:///home/user/opt/pencil-3.0.0-rc.2/app/views/editors/PropertyEditor.xhtml?t=1515510871010_3344 net::ERR_FILE_NOT_FOUNDloadNext @ Common.js:646request.onreadystatechange @ Common.js:641
Common.js:646 GET file:///home/user/opt/pencil-3.0.0-rc.2/app/views/menus/CanvasMenu.xhtml?t=1515510871010_3344 net::ERR_FILE_NOT_FOUNDloadNext @ Common.js:646request.onreadystatechange @ Common.js:641
Common.js:646 GET file:///home/user/opt/pencil-3.0.0-rc.2/app/views/menus/MainMenu.xhtml?t=1515510871010_3344 net::ERR_FILE_NOT_FOUNDloadNext @ Common.js:646request.onreadystatechange @ Common.js:641
Common.js:646 GET file:///home/user/opt/pencil-3.0.0-rc.2/app/views/menus/PageMenu.xhtml?t=1515510871010_3344 net::ERR_FILE_NOT_FOUNDloadNext @ Common.js:646request.onreadystatechange @ Common.js:641
Common.js:646 GET file:///home/user/opt/pencil-3.0.0-rc.2/app/views/menus/ChildPageListMenu.xhtml?t=1515510871010_3344 net::ERR_FILE_NOT_FOUNDloadNext @ Common.js:646request.onreadystatechange @ Common.js:641
Common.js:646 GET file:///home/user/opt/pencil-3.0.0-rc.2/app/views/collections/CollectionMenu.xhtml?t=1515510871010_3344 net::ERR_FILE_NOT_FOUNDloadNext @ Common.js:646request.onreadystatechange @ Common.js:641
Common.js:646 GET file:///home/user/opt/pencil-3.0.0-rc.2/app/views/collections/CollectionPane.xhtml?t=1515510871010_3344 net::ERR_FILE_NOT_FOUNDloadNext @ Common.js:646request.onreadystatechange @ Common.js:641
Common.js:646 GET file:///home/user/opt/pencil-3.0.0-rc.2/app/views/collections/MyCollectionPane.xhtml?t=1515510871010_3344 net::ERR_FILE_NOT_FOUNDloadNext @ Common.js:646request.onreadystatechange @ Common.js:641
Common.js:646 GET file:///home/user/opt/pencil-3.0.0-rc.2/app/views/collections/PrivateCollectionMenu.xhtml?t=1515510871010_3344 net::ERR_FILE_NOT_FOUNDloadNext @ Common.js:646request.onreadystatechange @ Common.js:641
Common.js:646 GET file:///home/user/opt/pencil-3.0.0-rc.2/app/views/collections/ShowAllCollectionMenu.xhtml?t=1515510871010_3344 net::ERR_FILE_NOT_FOUNDloadNext @ Common.js:646request.onreadystatechange @ Common.js:641
util.js:1191 ENOENT: no such file or directory, stat '/home/user/.pencil/privateCollection/PrivateCollection.xml'

Location: undefined (undefined)
Stacktrace:
	Error: ENOENT: no such file or directory, stat '/home/user/.pencil/privateCollection/PrivateCollection.xml'
	    at Error (native)
	    at fs.statSync (fs.js:992:18)
	    at Object.fs.statSync (ELECTRON_ASAR.js:280:16)
	    at Object.PrivateCollectionManager.loadPrivateCollections (file:///home/user/opt/pencil-3.0.0-rc.2/app/pencil-core/privateCollection/privateCollectionManager.js:14:23)
	    at MyCollectionPane.initialize (file:///home/user/opt/pencil-3.0.0-rc.2/app/views/collections/MyCollectionPane.js:22:30)
	    at MyCollectionPane.BaseCollectionPane [as constructor] (file:///home/user/opt/pencil-3.0.0-rc.2/app/views/collections/BaseCollectionPane.js:93:10)
	    at new MyCollectionPane (file:///home/user/opt/pencil-3.0.0-rc.2/app/views/collections/MyCollectionPane.js:2:24)
	    at file:///home/user/opt/pencil-3.0.0-rc.2/app/lib/widget/Common.js:174:26
	    at Object.Dom.doOnChildRecursively (file:///home/user/opt/pencil-3.0.0-rc.2/app/pencil-core/common/util.js:514:36)
	    at Object.performAutoBinding (file:///home/user/opt/pencil-3.0.0-rc.2/app/lib/widget/Common.js:159:17)Console.dumpError @ util.js:1191PrivateCollectionManager.loadPrivateCollections @ privateCollectionManager.js:31MyCollectionPane.initialize @ MyCollectionPane.js:22BaseCollectionPane @ BaseCollectionPane.js:93MyCollectionPane @ MyCollectionPane.js:2(anonymous function) @ Common.js:174Dom.doOnChildRecursively @ util.js:514performAutoBinding @ Common.js:159(anonymous function) @ Common.js:219Dom.doOnChildRecursively @ util.js:514Dom.doOnChildRecursively @ util.js:515Dom.doOnChildRecursively @ util.js:515performAutoBinding @ Common.js:159_processTemplate @ Common.js:234_toTemplateNode @ Common.js:361loadTemplateAsNodeSync @ Common.js:372BaseTemplatedWidget.buildDOMNode @ Common.js:832BaseWidget @ Common.js:654BaseTemplatedWidget @ Common.js:826ApplicationPane @ ApplicationPane.js:2(anonymous function) @ Common.js:174Dom.doOnChildRecursively @ util.js:514performAutoBinding @ Common.js:159onLoadDone @ Common.js:606loadNext @ Common.js:617request.onreadystatechange @ Common.js:641
collectionManager.js:169 Loading system stencils...
shapeDefCollectionParser.js:47 GET file:///home/user/opt/pencil-3.0.0-rc.2/app/stencils/Common/en-US.dtd ShapeDefCollectionParser.injectEntityDefsFromUrl @ shapeDefCollectionParser.js:47ShapeDefCollectionParser.parseURL @ shapeDefCollectionParser.js:71CollectionManager.loadStencils @ collectionManager.js:172Pencil.boot @ pencil.js:89ApplicationPane @ ApplicationPane.js:4(anonymous function) @ Common.js:174Dom.doOnChildRecursively @ util.js:514performAutoBinding @ Common.js:159onLoadDone @ Common.js:606loadNext @ Common.js:617request.onreadystatechange @ Common.js:641
shapeDefCollectionParser.js:47 GET file:///home/user/opt/pencil-3.0.0-rc.2/app/stencils/BasicWebElements/en-US.dtd ShapeDefCollectionParser.injectEntityDefsFromUrl @ shapeDefCollectionParser.js:47ShapeDefCollectionParser.parseURL @ shapeDefCollectionParser.js:71CollectionManager.loadStencils @ collectionManager.js:173Pencil.boot @ pencil.js:89ApplicationPane @ ApplicationPane.js:4(anonymous function) @ Common.js:174Dom.doOnChildRecursively @ util.js:514performAutoBinding @ Common.js:159onLoadDone @ Common.js:606loadNext @ Common.js:617request.onreadystatechange @ Common.js:641
shapeDefCollectionParser.js:47 GET file:///home/user/opt/pencil-3.0.0-rc.2/app/stencils/Gtk.GUI/en-US.dtd ShapeDefCollectionParser.injectEntityDefsFromUrl @ shapeDefCollectionParser.js:47ShapeDefCollectionParser.parseURL @ shapeDefCollectionParser.js:71CollectionManager.loadStencils @ collectionManager.js:174Pencil.boot @ pencil.js:89ApplicationPane @ ApplicationPane.js:4(anonymous function) @ Common.js:174Dom.doOnChildRecursively @ util.js:514performAutoBinding @ Common.js:159onLoadDone @ Common.js:606loadNext @ Common.js:617request.onreadystatechange @ Common.js:641
shapeDefCollectionParser.js:47 GET file:///home/user/opt/pencil-3.0.0-rc.2/app/stencils/SketchyGUI/en-US.dtd ShapeDefCollectionParser.injectEntityDefsFromUrl @ shapeDefCollectionParser.js:47ShapeDefCollectionParser.parseURL @ shapeDefCollectionParser.js:71CollectionManager.loadStencils @ collectionManager.js:175Pencil.boot @ pencil.js:89ApplicationPane @ ApplicationPane.js:4(anonymous function) @ Common.js:174Dom.doOnChildRecursively @ util.js:514performAutoBinding @ Common.js:159onLoadDone @ Common.js:606loadNext @ Common.js:617request.onreadystatechange @ Common.js:641
shapeDefCollectionParser.js:47 GET file:///home/user/opt/pencil-3.0.0-rc.2/app/stencils/WindowsXP-GUI/en-US.dtd ShapeDefCollectionParser.injectEntityDefsFromUrl @ shapeDefCollectionParser.js:47ShapeDefCollectionParser.parseURL @ shapeDefCollectionParser.js:71CollectionManager.loadStencils @ collectionManager.js:176Pencil.boot @ pencil.js:89ApplicationPane @ ApplicationPane.js:4(anonymous function) @ Common.js:174Dom.doOnChildRecursively @ util.js:514performAutoBinding @ Common.js:159onLoadDone @ Common.js:606loadNext @ Common.js:617request.onreadystatechange @ Common.js:641
shapeDefCollectionParser.js:47 GET file:///home/user/opt/pencil-3.0.0-rc.2/app/stencils/CommonShapes_Flowchart/en-US.dtd ShapeDefCollectionParser.injectEntityDefsFromUrl @ shapeDefCollectionParser.js:47ShapeDefCollectionParser.parseURL @ shapeDefCollectionParser.js:71CollectionManager.loadStencils @ collectionManager.js:178Pencil.boot @ pencil.js:89ApplicationPane @ ApplicationPane.js:4(anonymous function) @ Common.js:174Dom.doOnChildRecursively @ util.js:514performAutoBinding @ Common.js:159onLoadDone @ Common.js:606loadNext @ Common.js:617request.onreadystatechange @ Common.js:641
shapeDefCollectionParser.js:47 GET file:///home/user/opt/pencil-3.0.0-rc.2/app/stencils/Android.GUI/en-US.dtd ShapeDefCollectionParser.injectEntityDefsFromUrl @ shapeDefCollectionParser.js:47ShapeDefCollectionParser.parseURL @ shapeDefCollectionParser.js:71CollectionManager.loadStencils @ collectionManager.js:179Pencil.boot @ pencil.js:89ApplicationPane @ ApplicationPane.js:4(anonymous function) @ Common.js:174Dom.doOnChildRecursively @ util.js:514performAutoBinding @ Common.js:159onLoadDone @ Common.js:606loadNext @ Common.js:617request.onreadystatechange @ Common.js:641
shapeDefCollectionParser.js:47 GET file:///home/user/opt/pencil-3.0.0-rc.2/app/stencils/iOS.GUI/en-US.dtd ShapeDefCollectionParser.injectEntityDefsFromUrl @ shapeDefCollectionParser.js:47ShapeDefCollectionParser.parseURL @ shapeDefCollectionParser.js:71CollectionManager.loadStencils @ collectionManager.js:180Pencil.boot @ pencil.js:89ApplicationPane @ ApplicationPane.js:4(anonymous function) @ Common.js:174Dom.doOnChildRecursively @ util.js:514performAutoBinding @ Common.js:159onLoadDone @ Common.js:606loadNext @ Common.js:617request.onreadystatechange @ Common.js:641
util.js:1191 x is not defined

Location: undefined (undefined)
Stacktrace:
	ReferenceError: x is not defined
	    at eval (eval at pEval (file:///home/user/opt/pencil-3.0.0-rc.2/app/pencil-core/common/util.js:2068:35), <anonymous>:67:310962)
	    at pEval (file:///home/user/opt/pencil-3.0.0-rc.2/app/pencil-core/common/util.js:2068:35)
	    at file:///home/user/opt/pencil-3.0.0-rc.2/app/pencil-core/definition/shapeDefCollectionParser.js:213:9
	    at Object.Dom.workOn (file:///home/user/opt/pencil-3.0.0-rc.2/app/pencil-core/common/util.js:285:9)
	    at ShapeDefCollectionParser.parse (file:///home/user/opt/pencil-3.0.0-rc.2/app/pencil-core/definition/shapeDefCollectionParser.js:211:9)
	    at ShapeDefCollectionParser.parseURL (file:///home/user/opt/pencil-3.0.0-rc.2/app/pencil-core/definition/shapeDefCollectionParser.js:75:31)
	    at Object.CollectionManager.loadStencils (file:///home/user/opt/pencil-3.0.0-rc.2/app/pencil-core/definition/collectionManager.js:180:52)
	    at Object.Pencil.boot (file:///home/user/opt/pencil-3.0.0-rc.2/app/pencil-core/common/pencil.js:89:27)
	    at new ApplicationPane (file:///home/user/opt/pencil-3.0.0-rc.2/app/views/ApplicationPane.js:4:12)
	    at file:///home/user/opt/pencil-3.0.0-rc.2/app/lib/widget/Common.js:174:26Console.dumpError @ util.js:1191pEval @ util.js:2074(anonymous function) @ shapeDefCollectionParser.js:213Dom.workOn @ util.js:285ShapeDefCollectionParser.parse @ shapeDefCollectionParser.js:211ShapeDefCollectionParser.parseURL @ shapeDefCollectionParser.js:75CollectionManager.loadStencils @ collectionManager.js:180Pencil.boot @ pencil.js:89ApplicationPane @ ApplicationPane.js:4(anonymous function) @ Common.js:174Dom.doOnChildRecursively @ util.js:514performAutoBinding @ Common.js:159onLoadDone @ Common.js:606loadNext @ Common.js:617request.onreadystatechange @ Common.js:641
shapeDefCollectionParser.js:47 GET file:///home/user/opt/pencil-3.0.0-rc.2/app/stencils/iOS-Wireframe/en-US.dtd ShapeDefCollectionParser.injectEntityDefsFromUrl @ shapeDefCollectionParser.js:47ShapeDefCollectionParser.parseURL @ shapeDefCollectionParser.js:71CollectionManager.loadStencils @ collectionManager.js:181Pencil.boot @ pencil.js:89ApplicationPane @ ApplicationPane.js:4(anonymous function) @ Common.js:174Dom.doOnChildRecursively @ util.js:514performAutoBinding @ Common.js:159onLoadDone @ Common.js:606loadNext @ Common.js:617request.onreadystatechange @ Common.js:641
shapeDefCollectionParser.js:47 GET file:///home/user/opt/pencil-3.0.0-rc.2/app/stencils/Prototype_GUI/en-US.dtd ShapeDefCollectionParser.injectEntityDefsFromUrl @ shapeDefCollectionParser.js:47ShapeDefCollectionParser.parseURL @ shapeDefCollectionParser.js:71CollectionManager.loadStencils @ collectionManager.js:183Pencil.boot @ pencil.js:89ApplicationPane @ ApplicationPane.js:4(anonymous function) @ Common.js:174Dom.doOnChildRecursively @ util.js:514performAutoBinding @ Common.js:159onLoadDone @ Common.js:606loadNext @ Common.js:617request.onreadystatechange @ Common.js:641
collectionManager.js:136 Loading stencils in: /home/user/.pencil/stencils
 excluded: undefined
collectionManager.js:78 Loading developer stencils...
exportTemplateManager.js:100 Error: ENOENT: no such file or directory, stat '/home/user/.pencil/exportTemplates/HTML'(…)ExportTemplateManager._loadUserDefinedTemplatesIn @ exportTemplateManager.js:100ExportTemplateManager.loadTemplatesIn @ exportTemplateManager.js:32ExportTemplateManager.loadUserDefinedTemplates @ exportTemplateManager.js:43ExportTemplateManager.loadTemplates @ exportTemplateManager.js:112Pencil.boot @ pencil.js:90ApplicationPane @ ApplicationPane.js:4(anonymous function) @ Common.js:174Dom.doOnChildRecursively @ util.js:514performAutoBinding @ Common.js:159onLoadDone @ Common.js:606loadNext @ Common.js:617request.onreadystatechange @ Common.js:641
exportTemplateManager.js:100 Error: ENOENT: no such file or directory, stat '/home/user/.pencil/exportTemplates/Print'(…)ExportTemplateManager._loadUserDefinedTemplatesIn @ exportTemplateManager.js:100ExportTemplateManager.loadTemplatesIn @ exportTemplateManager.js:32ExportTemplateManager.loadUserDefinedTemplates @ exportTemplateManager.js:43ExportTemplateManager.loadTemplates @ exportTemplateManager.js:112Pencil.boot @ pencil.js:90ApplicationPane @ ApplicationPane.js:4(anonymous function) @ Common.js:174Dom.doOnChildRecursively @ util.js:514performAutoBinding @ Common.js:159onLoadDone @ Common.js:606loadNext @ Common.js:617request.onreadystatechange @ Common.js:641
exportTemplateManager.js:100 Error: ENOENT: no such file or directory, stat '/home/user/.pencil/exportTemplates/ODT'(…)ExportTemplateManager._loadUserDefinedTemplatesIn @ exportTemplateManager.js:100ExportTemplateManager.loadTemplatesIn @ exportTemplateManager.js:32ExportTemplateManager.loadUserDefinedTemplates @ exportTemplateManager.js:43ExportTemplateManager.loadTemplates @ exportTemplateManager.js:112Pencil.boot @ pencil.js:90ApplicationPane @ ApplicationPane.js:4(anonymous function) @ Common.js:174Dom.doOnChildRecursively @ util.js:514performAutoBinding @ Common.js:159onLoadDone @ Common.js:606loadNext @ Common.js:617request.onreadystatechange @ Common.js:641
exportTemplateManager.js:13 add template ExportTemplate {editableProperties: Array[0], id: "Evolus:HTML:Default.Template", name: "Default HTML Template", author: "Evolus", description: "Very simple HTML export template that lists all pages in a single document."…} HTML
exportTemplate.js:37 Type: ["Enum", function]
exportTemplate.js:37 Type: ["Enum", function]
exportTemplate.js:37 Type: ["Enum", function]
exportTemplate.js:37 Type: ["Enum", function]
exportTemplate.js:37 Type: ["Enum", function]
exportTemplate.js:37 Type: ["Color", function]
exportTemplateManager.js:13 add template ExportTemplate {editableProperties: Array[6], id: "Evolus:Print:Brochure", name: "Brochure Export Template", author: "Evolus", description: "A simple brochure printing template"…} Print
exportTemplate.js:37 Type: ["Enum", function]
exportTemplate.js:37 Type: ["Enum", function]
exportTemplate.js:37 Type: ["Enum", function]
exportTemplate.js:37 Type: ["Enum", function]
exportTemplate.js:37 Type: ["Enum", function]
exportTemplate.js:37 Type: ["Enum", function]
exportTemplate.js:37 Type: ["Enum", function]
exportTemplate.js:37 Type: ["Enum", function]
exportTemplate.js:37 Type: ["Enum", function]
exportTemplate.js:37 Type: ["Enum", function]
exportTemplateManager.js:13 add template ExportTemplate {editableProperties: Array[10], id: "Evolus:Print:Default.Template.Unified", name: "Default Export Template", author: "Evolus", description: "The default printing template with full options"…} Print
exportTemplateManager.js:13 add template ExportTemplate {editableProperties: Array[0], id: "Evolus:ODT:Default.Template", name: "Default Document Template", author: "Evolus", description: "Simple template for exporting to .ODT, .DOC and .PDF"…} ODT
util.js:1191 fontManager is not defined

Location: undefined (undefined)
Stacktrace:
	ReferenceError: fontManager is not defined
	    at Object.Local.getInstalledFonts (file:///home/user/opt/pencil-3.0.0-rc.2/app/pencil-core/common/util.js:1033:17)
	    at Function.FontEditor._loadFontItems (file:///home/user/opt/pencil-3.0.0-rc.2/app/views/editors/FontEditor.js:32:28)
	    at Function.FontEditor._setupFontCombo (file:///home/user/opt/pencil-3.0.0-rc.2/app/views/editors/FontEditor.js:25:16)
	    at SharedFontEditor.setup (file:///home/user/opt/pencil-3.0.0-rc.2/app/views/editors/SharedFontEditor.js:20:16)
	    at Object.Pencil.boot (file:///home/user/opt/pencil-3.0.0-rc.2/app/pencil-core/common/pencil.js:141:41)
	    at new ApplicationPane (file:///home/user/opt/pencil-3.0.0-rc.2/app/views/ApplicationPane.js:4:12)
	    at file:///home/user/opt/pencil-3.0.0-rc.2/app/lib/widget/Common.js:174:26
	    at Object.Dom.doOnChildRecursively (file:///home/user/opt/pencil-3.0.0-rc.2/app/pencil-core/common/util.js:514:36)
	    at Object.performAutoBinding (file:///home/user/opt/pencil-3.0.0-rc.2/app/lib/widget/Common.js:159:17)
	    at onLoadDone (file:///home/user/opt/pencil-3.0.0-rc.2/app/lib/widget/Common.js:606:21)Console.dumpError @ util.js:1191Pencil.boot @ pencil.js:143ApplicationPane @ ApplicationPane.js:4(anonymous function) @ Common.js:174Dom.doOnChildRecursively @ util.js:514performAutoBinding @ Common.js:159onLoadDone @ Common.js:606loadNext @ Common.js:617request.onreadystatechange @ Common.js:641
util.js:1033 Uncaught ReferenceError: fontManager is not definedLocal.getInstalledFonts @ util.js:1033FontEditor._loadFontItems @ FontEditor.js:32SharedFontEditor.reloadFontItems @ SharedFontEditor.js:89(anonymous function) @ pencil.js:152Dom.emitEvent @ util.js:555(anonymous function) @ FontLoader.js:52g @ events.js:286emitTwo @ events.js:106emit @ events.js:191
```

**Comment by h-2-0** [comment]
@dgthanhan Do you know which Electron version corresponds to Pencil 3.0.0.rc.2 ?

**Comment by h-2-0** [comment]
I also tried installing previous release (rc1) and use its own electron-prebuilt -which it seems it is 1.2.2- (`../pencil-3.0.0-rc.1/node_modules/electron-prebuilt/cli.js ./app` (with and withoug the --enable-dev flag)to run the rc2 version but it also failed.
