### ISSUE TITLE
pencil Checkout from source seems to fail to load 

### ISSUE THREAD

**Issue by granolocks** [evolus/pencil#302]
* Operating system: Ubuntu 16.04
* Pencil version: 21cc44e35ba93b76fe0926716f2439db318ff895

When I try to do `npm run` it seems like its starting and a window opens but the following is also logged: 

```
user@system:/home/user/code/js/pencil# npm start

> Pencil@ start /home/user/code/js/pencil
> electron ./app

Hardware acceleration disabled for Linux.
Platform: linux
{ Error: Cannot find module 'tmp'
    at Module._resolveFilename (module.js:455:15)
    at Function.Module._resolveFilename (/home/user/code/js/pencil/node_modules/electron/dist/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._load (module.js:403:25)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at /home/user/code/js/pencil/app/pencil-core/common/renderer.js:7:17
    at Object.<anonymous> (/home/user/code/js/pencil/app/pencil-core/common/renderer.js:205:2)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32) code: 'MODULE_NOT_FOUND' }
```

The window that loads looks like it is working,but the central icon just flashes steadily and the window can't be interacted with beyond basic GUI window functionality like minimize, close etc. 

![image](https://cloud.githubusercontent.com/assets/209583/24940361/9daaa568-1f10-11e7-94cb-bfbe5d8cdf49.png)

I'm probably missing something basic. Can you point me in the right direction?

**Comment by granolocks** [comment]
I ran `npm install tmp` and that helped the error message WRT `tmp` but the flashing window still remains all I get when i run `npm start`.

**Comment by dgthanhan** [comment]
Did you follow the instruction at https://github.com/evolus/pencil/blob/master/README.md for how to set up the dev?

**Comment by granolocks** [comment]
@dgthanhan I did. The node modules all installed fine but the app just hangs when it starts without any further errors.

**Comment by dgthanhan** [comment]
From what I saw above, you are installing separate modules manually which is not the correct way. The provided install script in the package.json has also instructions to grab the correct electron version and also the rebuild any native module if required.

Please follow the instructions and let me know if you still have problems.

**Comment by granolocks** [comment]
All I did was run `npm install` and `npm start`in a checkout of this repo using the latest LTS node. 

I'm not sure what other directions there are to follow.

**Comment by dgthanhan** [comment]
It looks like your npm is either old or its package registry is corrupted. `tmp` is clearly included as an app dependency so it should be installed automatically.

Make sure you are using at least Node 5+ and try to clean up package cache using `npm cache clean`.

You can also launch the Dev Tools using Ctrl + Shift + I to see the error log when the app got stuck.

**Comment by granolocks** [comment]
I have node version 6.10.2. `CTRL+SHIFT+I` dd not bring up an error console in the hung app. 

I ran `npm cache clean` and that didn't work. I rm'd `node_modules` and reinstalled everything, same exact issue.

**Comment by buithehoa** [comment]
@granolocks I'm on Ubuntu 16.10 and `Ctrl+Shift+Alt+P` will show the Console. Let me know if it works for you.

**Comment by gavinwade12** [comment]
I had this same issue on Mint 18.2. npm was failing to install all the app dependencies because of the source location. Moved it to a more friendly directory where I didn't have to use `sudo` and the application is working fine now.
