### ISSUE TITLE
Pencil does not start on manjaro

### ISSUE THREAD

**Issue by astrofrite** [evolus/pencil#721]
* Operating system: Manjaro 21.2.6 
* Pencil version: 3.1.0-7

When I launch pencil, it just display a white background with the logo blinking, and nothing else, if i launch it via command line, it outputs this : 

```bash
useHWAConfig:  undefined
Hardware acceleration disabled for Linux.
[6462:0524/141911.986922:ERROR:sandbox_linux.cc(377)] InitializeSandbox() called with multiple threads in process gpu-process.
Background web-printer started.
Shortcut main service started.
(node:6431) ProtocolDeprecateCallback: The callback argument of protocol module APIs is no longer needed.
```
I'v seen 1 issue like mine, i tried to change in the /usr/share/applications/pencil.desktop the `Exec="/usr/bin/pencil.sh"` but it does nothing. When I try to launch it with electron, it outputs this error : 
```bash 
App threw an error during load
/usr/bin/pencil:2
exec electron /usr/lib/pencil "$@"
     ^^^^^^^^

SyntaxError: Unexpected identifier
    at Object.compileFunction (node:vm:352:18)
    at wrapSafe (node:internal/modules/cjs/loader:1038:15)
    at Module._compile (node:internal/modules/cjs/loader:1072:27)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1169:10)
    at Module.load (node:internal/modules/cjs/loader:988:32)
    at Module._load (node:internal/modules/cjs/loader:829:12)
    at Function.c._load (node:electron/js2c/asar_bundle:5:13343)
    at loadApplicationPackage (/usr/lib/electron/resources/default_app.asar/main.js:110:16)
    at Object.<anonymous> (/usr/lib/electron/resources/default_app.asar/main.js:222:9)
    at Module._compile (node:internal/modules/cjs/loader:1116:14)
A JavaScript error occurred in the main process
Uncaught Exception:
/usr/bin/pencil:2
exec electron /usr/lib/pencil "$@"
     ^^^^^^^^

SyntaxError: Unexpected identifier
    at Object.compileFunction (node:vm:352:18)
    at wrapSafe (node:internal/modules/cjs/loader:1038:15)
    at Module._compile (node:internal/modules/cjs/loader:1072:27)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1169:10)
    at Module.load (node:internal/modules/cjs/loader:988:32)
    at Module._load (node:internal/modules/cjs/loader:829:12)
    at Function.c._load (node:electron/js2c/asar_bundle:5:13343)
    at loadApplicationPackage (/usr/lib/electron/resources/default_app.asar/main.js:110:16)
    at Object.<anonymous> (/usr/lib/electron/resources/default_app.asar/main.js:222:9)
    at Module._compile (node:internal/modules/cjs/loader:1116:14)
[6878:0524/142516.156745:ERROR:sandbox_linux.cc(377)] InitializeSandbox() called with multiple threads in process gpu-process.
``` 

I'm new with manjaro so maybe it's an issue with how I installed it.

**Comment by Digoya** [comment]
There is a discussion about this issue on [AUR](https://aur.archlinux.org/packages/pencil). Running pencil from [electron11](https://aur.archlinux.org/packages/electron11-bin) worked for me well. 

After installation just run `electron11 /usr/lib/pencil/ `

**Comment by rofaccess** [comment]
The pencil 3.1.0-7 was worked for me in Manjaro using electron11 /usr/lib/pencil/, but currently not work.
Actually I using pencil-git from AUR that work without problems, and, is not necessary the command using electron11.
Other alternatives:
- Install pencil-snap-demo 3.0.4 from Snap but the UI is a little different.
- Download and install in opt/ folder the installer from [here](https://pencil.evolus.vn/dl/development/Pencil-3.1.0.20221208133012.tar.gz)
